name: Deploy Airflow DAGs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies for validation
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Check for requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found."
            exit 1
          fi

      - name: Lint Python Code with flake8
        run: |
          flake8 dags/
      
      - name: Format Python Code with black
        run: |
          black --check dags/

      - name: Validate requirements.txt
        run: |
          pip install -r requirements.txt

      - name: Deploy DAGs
        run: |
          echo "Deploying project..."

          sudo mkdir -p $AIRFLOW_HOME/dags
          sudo mkdir -p $AIRFLOW_HOME/data
          sudo mkdir -p $AIRFLOW_HOME/functions

          sudo chown -R $USER:$USER $AIRFLOW_HOME

          cp -r ./dags/* $AIRFLOW_HOME/dags/
          cp -r ./data/* $AIRFLOW_HOME/data/
          cp -r ./functions/* $AIRFLOW_HOME/functions/